In [1]:
# 2.	Create representation of document by calculating Term Frequency and Inverse Document Frequency.

In [2]:
import pandas as pd
import sklearn as sk
import math
first_sentence = "Data Science is the sexiest job of the 21st century"
second_sentence = "machine learning is the key for data science"
#split so each word have their own string
first_sentence = first_sentence.split(" ")
second_sentence = second_sentence.split(" ")
#join them to remove comon duplicate words
total = set(first_sentence).union(set(second_sentence))
print(total)

{'key', 'is', 'job', 'machine', 'of', 'century', 'for', 'sexiest', 'Science', '21st', 'learning', 'science', 'Data', 'the', 'data'}

In [4]:
wordDictA = dict.fromkeys(total, 0)
wordDictB = dict.fromkeys(total, 0)
# The full form of "dict" in Python refers to a "dictionary."
for word in first_sentence:
 wordDictA[word]+=1
for word in second_sentence:
 wordDictB[word]+=1
pd.DataFrame([wordDictA, wordDictB])

,key,is,job,machine,of,century,for,sexiest,Science,21st,learning,science,Data,the,data
0,0,1,1,0,1,1,0,1,1,1,0,0,1,2,0
1,1,1,0,1,0,0,1,0,0,0,1,1,0,1,1

In [6]:
def computeTF(wordDict, doc):
 tfDict = {}
 corpusCount = len(doc)
 for word, count in wordDict.items():
     tfDict[word] = count/float(corpusCount)
 return(tfDict)
#running our sentences through the tf function:
tfFirst = computeTF(wordDictA, first_sentence)
tfSecond = computeTF(wordDictB, second_sentence)
#Converting to dataframe for visualization
pd.DataFrame([tfFirst, tfSecond])

,key,is,job,machine,of,century,for,sexiest,Science,21st,learning,science,Data,the,data
0,0.000,0.100,0.1,0.000,0.1,0.1,0.000,0.1,0.1,0.1,0.000,0.000,0.1,0.200,0.000
1,0.125,0.125,0.0,0.125,0.0,0.0,0.125,0.0,0.0,0.0,0.125,0.125,0.0,0.125,0.125

In [8]:
import math
import pandas as pd
def computeIDF(docList):
 idfDict = {}
 N = len(docList)
 for doc in docList:
     for word in doc:
         if word not in idfDict:
             idfDict[word] = 0
         idfDict[word] += 1
 for word, val in idfDict.items():
     idfDict[word] = math.log10(N / float(val)+ 1)
 return idfDict
    
def computeTFIDF(tfBow, idfs):
 tfidf = {}
 N = len(tfBow)
 for word, val in tfBow.items():
     tfidf[word] = val * idfs.get(word, 0)
 return tfidf
# Example usage
docList = [wordDictA, wordDictB]
idfs = computeIDF(docList)
tfidfA = computeTFIDF(wordDictA, idfs)
tfidfB = computeTFIDF(wordDictB, idfs)
df = pd.DataFrame([tfidfA, tfidfB])
print(df)

       key       is      job  machine       of  century      for  sexiest  \
0  0.00000  0.30103  0.30103  0.00000  0.30103  0.30103  0.00000  0.30103
1  0.30103  0.30103  0.00000  0.30103  0.00000  0.00000  0.30103  0.00000

   Science     21st  learning  science     Data      the     data
0  0.30103  0.30103   0.00000  0.00000  0.30103  0.60206  0.00000
1  0.00000  0.00000   0.30103  0.30103  0.00000  0.30103  0.30103